
version: '3.7'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    ports:
      - $ELASTIC_PORT_MAIN:$ELASTIC_PORT_MAIN
      - $ELASTIC_PORT_SECONDARY:$ELASTIC_PORT_SECONDARY
    environment:
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.monitoring.enabled: "true"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      xpack.security.enabled: $ELASTIC_SECURITY
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    ports:
      - $KIBANA_PORT:$KIBANA_PORT
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:$ELASTIC_PORT_MAIN
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    depends_on:
      - elasticsearch

  nestjs:
    image: nestjs:1.0.0
    build: ./nestjs/.
    volumes:
      - ./nestjs:/app
      - /app/node_modules
    env_file: ./nestjs/.env
    # command: npm run start:prod
    depends_on:
      - elasticsearch 
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - nestjs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email carlosalito@gmail.com --agree-tos --no-eff-email --force-renewal -d idheaconsult.com.br  -d www.idheaconsult.com.br

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /root/beautybook/backend/nestjs/dist/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/beautybook/backend/dhparam/
      o: bind
  esdata:
    driver: local

networks:
  app-network:
    driver: bridge