name: beautybook
description: A Microblogging Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  firebase_core: "^0.5.3"
  firebase_auth: "^0.18.4"
  cloud_firestore: "^0.14.3"
  firebase_storage: "^5.0.1"
  auto_route: ^0.6.9
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  injectable: ^1.0.5
  json_annotation: ^3.1.0
  get_it: ^5.0.1
  equatable: ^1.2.5
  flushbar: ^1.10.4
  ff_navigation_bar: ^0.1.4
  image_picker: ^0.6.7+17
  image_cropper: ^1.1.0
  photo_view: ^0.10.3
  cached_network_image: ^2.4.1
  flare_flutter: ^2.0.6
  flutter_i18n: ^0.19.4
  path_provider: ^1.6.24
  google_sign_in: ^4.5.6
  flutter_facebook_login: ^3.0.0
  
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.0

dev_dependencies:
  json_serializable: ^3.5.1
  build_runner: ^1.10.11
  hive_generator: ^0.8.2
  flutter_launcher_icons: ^0.8.1
  auto_route_generator: ^0.6.10
  mobx_codegen: ^1.1.2
  injectable_generator: ^1.0.6  
  mockito: ^4.1.3

  
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/launch.png'

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/i18n/

  fonts:
    - family: Colfax
      fonts:
        - asset: assets/fonts/Colfax-Regular.otf
        - asset: assets/fonts/Colfax-MediumItalic.otf
          style: italic
        - asset: assets/fonts/Colfax-Bold.otf
          weight: 700
        - asset: assets/fonts/Colfax-Medium.otf
          weight: 500
    - family: BeautybookIcons
      fonts:
        - asset: assets/fonts/beautybook.ttf
    
