name: beautybook
description: A Microblogging Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  firebase_core: "^0.5.2"
  firebase_auth: "^0.18.3"
  cloud_firestore: "^0.14.3"
  firebase_storage: "^5.0.1"
  auto_route: ^0.6.9
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  injectable: ^1.0.5
  json_annotation: ^3.1.0
  get_it: ^5.0.1
  equatable: ^1.2.5
  flushbar: ^1.10.4
  ff_navigation_bar: ^0.1.4
  image_picker: ^0.6.1+8
  image_cropper: ^1.1.0
  photo_view: ^0.10.3


  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.0

dev_dependencies:
  json_serializable: ^3.5.1
  build_runner: ^1.10.11
  hive_generator: ^0.8.2
  flutter_launcher_icons: ^0.8.1

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

